stages:
  split:
    cmd: python src/data/1_data_split.py
    deps:
    - data/raw_data
    - src/data/1_data_split.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/2_normalize.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/2_normalize.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/3_grid_search.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/3_grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python src/models/4_training.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/4_training.py
    outs:
    - models/gbr_model.pkl
  evaluate:
    cmd: python src/models/5_evaluate.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/gbr_model.pkl
    - src/models/5_evaluate.py
    outs:
    - metrics/scores.json
